/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.peluqueria;

/**
 *
 * @author Juan David
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jTextField82 = new javax.swing.JTextField();
        jTextField83 = new javax.swing.JTextField();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jTextField86 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 12, -1, -1));

        jTextField1.setFont(new java.awt.Font("Showcard Gothic", 0, 48)); // NOI18N
        jTextField1.setText("PELUQUERIA UDEC");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 440, 100));

        jTextField2.setText("ANA");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jTextField3.setText("JOSE");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jTextField4.setText("ROBERTO");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jTextField5.setText("LUCRECIA");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jTextField6.setText("CORTE CABALLERO");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jTextField7.setText("CORTE DAMA");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jTextField8.setText("TINTURA CABELLO");
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        jTextField9.setText("PEINADO");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        jTextField10.setText("TOTAL SERVICIOS");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jTextField11.setText("TOTAL RECAUDOS");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jButton1.setText("INICIAR DIA");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        jButton2.setText("REGISTRAR ANA");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, -1, -1));

        jButton3.setText("REGISTRAR ROBERTO");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, -1, -1));

        jButton4.setText("REGISTRAR LUCRECIA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jButton5.setText("REGISTRAR JOSE");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, -1, -1));

        jButton6.setText("VER TOTALES ");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        jButton7.setText("SALIR");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, -1, -1));

        jTextField46.setText("CORTE DAMA");
        jTextField46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField46ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField46, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jTextField47.setText("TINTURA CABELLO");
        getContentPane().add(jTextField47, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        jTextField48.setText("PEINADO");
        jTextField48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField48ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        jTextField49.setText("TOTAL SERVICIOS");
        getContentPane().add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jTextField50.setText("TOTAL RECAUDOS");
        getContentPane().add(jTextField50, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        jTextField51.setText("CORTE CABALLERO");
        getContentPane().add(jTextField51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jTextField52.setText("CORTE DAMA");
        jTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField52ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jTextField53.setText("TINTURA CABELLO");
        getContentPane().add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        jTextField54.setText("PEINADO");
        jTextField54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField54ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField54, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jTextField55.setText("TOTAL SERVICIOS");
        getContentPane().add(jTextField55, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        jTextField56.setText("TOTAL RECAUDOS");
        getContentPane().add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jTextField57.setText("CORTE CABALLERO");
        getContentPane().add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        jTextField58.setText("CORTE DAMA");
        jTextField58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField58ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField58, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        jTextField59.setText("TINTURA CABELLO");
        getContentPane().add(jTextField59, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, -1, -1));

        jTextField60.setText("PEINADO");
        jTextField60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField60ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        jTextField61.setText("TOTAL SERVICIOS");
        getContentPane().add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        jTextField62.setText("TOTAL RECAUDOS");
        getContentPane().add(jTextField62, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));
        getContentPane().add(jTextField63, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 80, -1));
        getContentPane().add(jTextField65, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 80, -1));
        getContentPane().add(jTextField66, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 80, -1));
        getContentPane().add(jTextField67, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, 20));
        getContentPane().add(jTextField68, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 80, -1));

        jTextField64.setText("CORTE CABALLERO");
        getContentPane().add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));
        getContentPane().add(jTextField69, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 70, -1));
        getContentPane().add(jTextField70, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 70, -1));
        getContentPane().add(jTextField71, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 70, -1));
        getContentPane().add(jTextField72, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 70, -1));
        getContentPane().add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 70, 20));
        getContentPane().add(jTextField74, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 70, -1));
        getContentPane().add(jTextField75, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, -1));
        getContentPane().add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 80, -1));
        getContentPane().add(jTextField77, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 80, -1));
        getContentPane().add(jTextField78, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 80, -1));
        getContentPane().add(jTextField79, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 80, 20));
        getContentPane().add(jTextField80, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 80, -1));
        getContentPane().add(jTextField81, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 70, -1));
        getContentPane().add(jTextField82, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 70, -1));
        getContentPane().add(jTextField83, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 70, -1));
        getContentPane().add(jTextField84, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 70, -1));
        getContentPane().add(jTextField85, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 70, 20));
        getContentPane().add(jTextField86, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField46ActionPerformed

    private void jTextField48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField48ActionPerformed

    private void jTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField52ActionPerformed

    private void jTextField54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField54ActionPerformed

    private void jTextField58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField58ActionPerformed

    private void jTextField60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField60ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField83;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField86;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
